service: my-s3-service

custom:
  wsgi:
    app: app.app
    packRequirements: false  
  bucketName: myrandombucket

provider:
  name: aws
  runtime: python3.9
  region: us-west-2
  environment:
    VARIABLE_1: supersecret99
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "*"

package:
  individually: true
  include:
    - app.py
    - requirements.txt
  exclude:
    - venv/**
    - node_modules/**
plugins:
  - serverless-s3-deploy
  - serverless-python-requirements
  - serverless-wsgi

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}    
        AccessControl: Private
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'



